### ISSUE TITLE
Missed Descriptors

### ISSUE THREAD

**Issue by Diefenthal** [Cinegy/TsDecoder#9]
I Missed some Descriptors

for that had i customized the descriptor class to

```
public Descriptor(byte[] stream, int start)
        {
            DescriptorTag = stream[start];
            DescriptorLength = stream[start + 1];
            Data = new byte[stream[start + 1]];
            Buffer.BlockCopy(stream, start + 2, Data, 0, stream[start + 1]);
        }
        public byte DescriptorTag { get; }
        public byte DescriptorLength { get; }
        public byte[] Data { get; set; }

        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.AppendFormat("\r\n");
            sb.AppendFormat("DVB Descriptor\r\n");
            sb.AppendFormat("DescriptorTag : {0},(0x{1})\r\n", DescriptorTag.ToString(), DescriptorTag.ToString("x2"));
            sb.AppendFormat("DescriptorLength : {0},(0x{1})\r\n", DescriptorLength.ToString(), DescriptorLength.ToString("x2"));
            sb.AppendFormat("DescriptorData : {0}\r\n", Utils.ToHexString(Data));
            sb.AppendFormat("\r\n");
            return sb.ToString();
        }
```

so had i the Chance to log the data of the Descriptors 
the dumps are here attached 
[Descriptor Dumps.zip](https://github.com/Cinegy/TsDecoder/files/1116985/Descriptor.Dumps.zip)

**Comment by lewk2** [comment]
This all looks reasonably sensible - the dumps help a huge amount (at least for testing - i hate doing this stuff blind).
I added just now the start of AC3 and EAC3 descriptors (just need to add the loops to read flagged elements, but need to collect some more sample streams first). Adding other ones... I will try and get around to it, but it might take a few weeks :-)

**Comment by Diefenthal** [comment]
if you want  tell me an date and timerange and i give you Access to my System over TeamViewer 
there had you then Vs 2017  some satip servers with dvbs  wireshark and what you Need

**Comment by Diefenthal** [comment]
as Addition to the descriptor text dumps here 2 capture files 
[11720 -2017-07-09-16-01-43.zip](https://github.com/Cinegy/TsDecoder/files/1133793/11720.-2017-07-09-16-01-43.zip)
[11954 -2017-07-09-16-05-06.zip](https://github.com/Cinegy/TsDecoder/files/1133794/11954.-2017-07-09-16-05-06.zip)

**Comment by lewk2** [comment]
I have completed the concrete ac3/eac3 descriptors, but rather than add just a few other random descriptors you found I added a pretty exhaustive dictionary of descriptor names and added a short & full name properties to the base class. Now all any descriptor should be correctly labelled and easy to access. I added your streams and some more unit tests (I do need to deal with some EIT bugs still...).

Let me know if there were any specific descriptors that you would appreciate concrete implementations and I can add them - but otherwise I would like to close this issue.

**Comment by Diefenthal** [comment]
you can Close this issue . sure there are many descriptors that can be needed but i try to help you in the future  with pull requests

the CADescriptor 0x09 look in one top post as exsample 
the other question is is it possible to use the Utils class? 

i looks cleaner in the descriptor cable satellite System Delivery descriptor if you use this 

`Frequency = Utils.ConvertBCDToInt(byteData, lastIndex, 8);`
instead of 
`Frequency = System.String.Format("{0}{1}{2}{3}{4}{5}{6}{7}", (stream[start + 2] >> 4) & 0x0F, stream[start + 2] & 0x0F, (stream[start + 3] >> 4) & 0x0F, stream[start + 3] & 0x0F, (stream[start + 4] >> 4) & 0x0F, stream[start + 4] & 0x0F, (stream[start + 5] >> 4) & 0x0F, stream[start + 5] & 0x0F);
`

**Comment by lewk2** [comment]
I had an issue i needed to fix with the EIT system, so while i was there i quickly added a concrete CA Descriptor.

I would probably use such a string format method if i need to touch such code again, but the satellite stuff came from a pull request from Chris - and so i'm a but loath to touch it just for improving readability.

If I do have any other reason to maintain anything (or if during adding any other descriptors it makes sense) then i'd be happy to.

I'm not so wild about the '2 bytes to int' helpers, since actually maintaining the indexing in such cases leads to more lines and it is harder to follow the location within the spec if debugging (since you need to do the math in your head instead or use debugger). If you see my implementation of the CA descriptor i think it expresses intent a little more clearly.

That example from the satellite descriptor is an ugly case though :-)
